# Generated by Django 5.0.14 on 2025-04-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "client_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "theater_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "theater_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "excel_theater_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "region_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "theater_kind",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_operator",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "legal_entity_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_address",
                    models.CharField(blank=True, max_length=2550, null=True),
                ),
                (
                    "representative_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "settlement_department",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "settlement_mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "settlement_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fax_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "settlement_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "representative_phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "invoice_email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "invoice_email_address2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("settlement_remarks", models.TextField(blank=True, null=True)),
                ("operational_status", models.BooleanField(blank=True, null=True)),
                (
                    "distributor_theater_name",
                    models.CharField(blank=True, default="N", max_length=10, null=True),
                ),
                ("login_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "login_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fare", models.CharField(blank=True, max_length=10, null=True)),
                ("fare_remark", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_client",
                        to="client.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auditorium", models.CharField(blank=True, max_length=10, null=True)),
                ("seat_count", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "auditorium_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theater_client",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
