# Generated by Django 5.0.14 on 2026-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_client_create_user_client_update_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="settlement_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
