# Generated by Django 5.0.14 on 2026-01-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_client_settlement_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="by4m_theater_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
