# Generated by Django 5.0.14 on 2026-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_client_by4m_theater_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_car",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
