# Generated by Django 5.0.14 on 2026-01-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_client_is_car"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="is_car",
            new_name="is_car_theater",
        ),
    ]
