# Generated by Django 5.0.14 on 2026-01-10 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_rename_is_car_client_is_car_theater"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorTheaterMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distributor_theater_name",
                    models.CharField(max_length=255, verbose_name="배급사측 극장명"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theater_maps",
                        to="client.client",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributor_mappings",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("distributor", "theater")},
            },
        ),
    ]
