# Generated by Django 5.0.14 on 2026-01-10 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_distributortheatermap"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="distributortheatermap",
            options={"ordering": ["-apply_date", "distributor_theater_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="distributortheatermap",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="distributortheatermap",
            name="apply_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="적용 시작일"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="distributortheatermap",
            unique_together={("distributor", "theater", "apply_date")},
        ),
    ]
