# Generated by Django 5.0.14 on 2026-06-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_alter_distributortheatermap_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="kofic_theater_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="theater",
            name="kofic_auditorium_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
