# Generated by Django 5.0.14 on 2026-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_client_kofic_theater_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="excel_theater_name2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
