# Generated by Django 5.0.14 on 2026-07-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_client_excel_theater_name2"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="rate_exception_type",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
