# Generated by Django 5.0.14 on 2026-08-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0014_settlement_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="kobis_linked",
            field=models.BooleanField(default=True),
        ),
    ]
