# Generated by Django 4.2.16 on 2026-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_client_kobis_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='kofic_theater_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
