# Generated by Django 5.0.14 on 2026-08-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0016_client_kofic_theater_name2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="settlement_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
