# Generated by Django 5.0.14 on 2025-05-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
