# Generated by Django 5.0.14 on 2025-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_remark_order_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
