# Generated by Django 5.0.14 on 2026-01-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_create_user_order_update_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
    ]
