# Generated by Django 4.2.16 on 2026-01-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_create_user_movie_update_user'),
        ('order', '0006_order_is_auto_generated_orderlist_is_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderlist_movie', to='movie.movie', verbose_name='대상 영화'),
        ),
    ]
