# Generated by Django 4.2.16 on 2026-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('entry_date', 'client', 'movie', 'auditorium', 'fare', 'show_count'), name='unique_score_record'),
        ),
    ]
