# Generated by Django 4.2.16 on 2026-08-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_score_create_user_score_update_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
