# Generated by Django 4.2.16 on 2026-01-29 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CGVScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=10)),
                ('theater_name', models.CharField(blank=True, max_length=100)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LotteScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=20)),
                ('theater_name', models.CharField(max_length=100)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MegaboxScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=20)),
                ('theater_name', models.CharField(max_length=50)),
                ('response_json', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('CGV', 'CGV'), ('LOTTE', 'Lotte Cinema'), ('MEGABOX', 'Megabox'), ('OTHER', 'Other')], default='CGV', max_length=20)),
                ('theater_name', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_booking_available', models.BooleanField(default=True)),
                ('booking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.cgvschedulelog')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time'], name='crawler_mov_start_t_f9d825_idx'), models.Index(fields=['brand', 'theater_name'], name='crawler_mov_brand_fd241d_idx')],
                'unique_together': {('brand', 'theater_name', 'screen_name', 'start_time')},
            },
        ),
    ]
