# Generated by Django 4.2.16 on 2026-01-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawlerrunhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrunhistory',
            name='trigger_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlerrunhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('STOP_REQUESTED', 'Stop Requested'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20),
        ),
    ]
