# Generated by Django 4.2.16 on 2026-01-30 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawlerrunhistory_trigger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgvschedulelog',
            name='crawler_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cgv_logs', to='crawler.crawlerrunhistory'),
        ),
        migrations.AddField(
            model_name='lotteschedulelog',
            name='crawler_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotte_logs', to='crawler.crawlerrunhistory'),
        ),
        migrations.AddField(
            model_name='megaboxschedulelog',
            name='crawler_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megabox_logs', to='crawler.crawlerrunhistory'),
        ),
    ]
