# Generated by Django 4.2.16 on 2026-01-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_cgvschedulelog_crawler_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crawlerrunhistory',
            name='trigger_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled'), ('TRANSFORM', 'Transform')], default='MANUAL', max_length=20),
        ),
    ]
