# Generated by Django 4.2.16 on 2026-01-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_movieschedule_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='remaining_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='total_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
