# Generated by Django 5.0.14 on 2026-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0006_movieschedule_remaining_seats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieschedule",
            name="play_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
