# Generated by Django 5.0.14 on 2026-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0007_movieschedule_play_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="megaboxschedulelog",
            unique_together={("query_date", "site_code")},
        ),
    ]
