# Generated by Django 5.0.14 on 2026-02-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0008_megaboxschedulelog_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lotteschedulelog",
            unique_together={("query_date", "theater_name")},
        ),
    ]
