# Generated by Django 5.0.14 on 2026-02-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0009_lotteschedulelog_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cgvschedulelog",
            unique_together={("query_date", "site_code")},
        ),
    ]
