# Generated by Django 5.0.14 on 2026-02-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0010_cgvschedulelog_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlTargetMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="영화 제목")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "크롤 대상 영화",
                "ordering": ["-created_at"],
            },
        ),
    ]
