# Generated by Django 5.0.14 on 2026-06-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0013_remove_crawltargetmovie_cinema_date_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieschedule",
            name="brand",
            field=models.CharField(
                choices=[
                    ("CGV", "CGV"),
                    ("LOTTE", "Lotte Cinema"),
                    ("MEGABOX", "Megabox"),
                    ("일반극장", "일반극장"),
                    ("OTHER", "Other"),
                ],
                default="CGV",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="KobisScheduleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_date", models.CharField(max_length=8)),
                ("site_code", models.CharField(max_length=20)),
                ("theater_name", models.CharField(blank=True, max_length=100)),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="success", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crawler_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kobis_logs",
                        to="crawler.crawlerrunhistory",
                    ),
                ),
            ],
            options={
                "unique_together": {("query_date", "site_code")},
            },
        ),
    ]
