# Generated by Django 5.0.14 on 2026-07-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0018_seed_cineq_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="KobisDistributorAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="배급사명")),
                ("user", models.CharField(max_length=100, verbose_name="아이디")),
                ("password", models.CharField(max_length=100, verbose_name="비밀번호")),
                (
                    "aprv_no",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="인증번호"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("sort_order", models.IntegerField(default=0, verbose_name="정렬순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "KOBIS 배급사 계정",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
