# Generated by Django 5.0.14 on 2026-09-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0021_crawlerscheduleconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlTitleAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crawl_title",
                    models.CharField(max_length=500, verbose_name="크롤링 영화명"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="crawler.crawltargetmovie",
                        verbose_name="대표 영화(크롤 대상)",
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤 영화명 매핑",
                "ordering": ["-created_at"],
            },
        ),
    ]
