# Generated by Django 5.0.14 on 2026-07-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0013_seed_rate_exception_theaters"),
        ("movie", "0014_movie_distributor_2_movie_distributor_3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yyyymm", models.CharField(max_length=7, verbose_name="부금년월")),
                (
                    "supply_delta",
                    models.IntegerField(default=0, verbose_name="공급가액 조정액"),
                ),
                (
                    "vat_delta",
                    models.IntegerField(default=0, verbose_name="부가세 조정액"),
                ),
                (
                    "payout_delta",
                    models.IntegerField(default=0, verbose_name="지급금 조정액"),
                ),
                (
                    "supply_original",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="조정 전 공급가액"
                    ),
                ),
                (
                    "vat_original",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="조정 전 부가세"
                    ),
                ),
                (
                    "payout_original",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="조정 전 지급금"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="비고"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="극장",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie.movie",
                        verbose_name="대표영화",
                    ),
                ),
            ],
            options={
                "verbose_name": "부금 정산 수동조정",
                "unique_together": {("yyyymm", "movie", "client")},
            },
        ),
    ]
