# Generated by Django 5.0.14 on 2026-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_seed_rate_exception_theaters"),
        ("movie", "0014_movie_distributor_2_movie_distributor_3_and_more"),
        ("settlement", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="settlementadjustment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="settlementadjustment",
            name="screen_format",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="상영 포맷"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="settlementadjustment",
            unique_together={("yyyymm", "movie", "client", "screen_format")},
        ),
    ]
