# Generated by Django 5.0.14 on 2026-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0002_alter_settlementadjustment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiParseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(max_length=64, verbose_name="파일 sha256"),
                ),
                ("model", models.CharField(max_length=64, verbose_name="AI 모델")),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("result", models.JSONField(verbose_name="추출 결과")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "부금정산서 AI 추출 캐시",
                "unique_together": {("file_hash", "model")},
            },
        ),
    ]
