# Generated by Django 5.0.14 on 2026-07-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_seed_rate_exception_theaters"),
        ("movie", "0014_movie_distributor_2_movie_distributor_3_and_more"),
        ("settlement", "0003_aiparsecache"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementConfirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yyyymm", models.CharField(max_length=7, verbose_name="부금년월")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="수동",
                        max_length=20,
                        verbose_name="확인 경로",
                    ),
                ),
                (
                    "confirmed_by",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="확인자"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.client",
                        verbose_name="극장",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie.movie",
                        verbose_name="대표영화",
                    ),
                ),
            ],
            options={
                "verbose_name": "부금 정산 확인",
                "unique_together": {("yyyymm", "movie", "client")},
            },
        ),
    ]
