# Generated by Django 5.0.14 on 2026-07-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settlement", "0005_backfill_confirms_from_adjustments"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementadjustment",
            name="date_to_original",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="조정 전 날짜(To)"
            ),
        ),
        migrations.AddField(
            model_name="settlementadjustment",
            name="date_to_override",
            field=models.DateField(
                blank=True, null=True, verbose_name="날짜(To) 조정값"
            ),
        ),
    ]
