# Generated by Django 4.2.16 on 2026-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_settlementadjustment_date_to_original_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlementadjustment',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='settlementadjustment',
            index=models.Index(fields=['yyyymm', 'movie', 'client', 'screen_format'], name='settlement__yyyymm_a69e29_idx'),
        ),
    ]
