# Generated by Django 4.2.16 on 2026-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0007_alter_settlementadjustment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementadjustment',
            name='date_to_is_bulk',
            field=models.BooleanField(default=False, verbose_name='현재 확정값이 일괄 수정분인지'),
        ),
        migrations.AddField(
            model_name='settlementadjustment',
            name='date_to_prev',
            field=models.DateField(blank=True, null=True, verbose_name='일괄 수정 전 확정값(수기/AI)'),
        ),
    ]
