# Generated by Django 4.2.16 on 2026-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timetable_access',
            field=models.BooleanField(default=True, verbose_name='시간표 조회 접근 권한'),
        ),
    ]
