# Generated by Django 5.0.14 on 2026-06-30 06:26

import django.db.models.deletion
import mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movie", "0014_movie_distributor_2_movie_distributor_3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementTargetMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="메일에서 다르게 표기되는 경우를 위한 별칭. 한 줄에 하나씩 입력.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_target",
                        to="movie.movie",
                        verbose_name="대상 영화",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산서 대상 영화",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectedSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=255)),
                ("month", models.CharField(db_index=True, max_length=7)),
                (
                    "matched_keyword",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("matched_in", models.CharField(blank=True, default="", max_length=20)),
                ("mail_folder", models.CharField(max_length=255)),
                ("mail_uid", models.IntegerField()),
                (
                    "mail_subject",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("mail_from", models.CharField(blank=True, default="", max_length=255)),
                ("mail_date", models.DateTimeField(blank=True, null=True)),
                ("attachment_index", models.IntegerField()),
                ("filename", models.CharField(max_length=500)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("size", models.IntegerField(default=0)),
                (
                    "file",
                    models.FileField(upload_to=mail.models.settlement_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_settlements",
                        to="movie.movie",
                    ),
                ),
            ],
            options={
                "ordering": ["-mail_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["month", "movie"], name="mail_collec_month_879dda_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="collectedsettlement",
            constraint=models.UniqueConstraint(
                fields=("mail_folder", "mail_uid", "attachment_index"),
                name="uniq_collected_attachment",
            ),
        ),
    ]
