# Generated by Django 5.0.14 on 2026-06-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
        ("movie", "0014_movie_distributor_2_movie_distributor_3_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectedsettlement",
            name="uniq_collected_attachment",
        ),
        migrations.AddConstraint(
            model_name="collectedsettlement",
            constraint=models.UniqueConstraint(
                fields=("mail_folder", "mail_uid", "attachment_index", "movie"),
                name="uniq_collected_attachment_movie",
            ),
        ),
    ]
