# Generated by Django 5.0.14 on 2026-07-31 11:56

from django.db import migrations, models


def backfill_from_collected(apps, schema_editor):
    """이미 수집된 메일(CollectedSettlement)을 수집 이력에 채워 넣는다.

    이 작업이 없으면 배포 직후 이력이 비어 있어, 이미 수집해둔 메일이 다음 스캔에서
    한 번 더 수집된다.
    """
    CollectedSettlement = apps.get_model("mail", "CollectedSettlement")
    CollectedMailLog = apps.get_model("mail", "CollectedMailLog")

    seen = {}
    rows = CollectedSettlement.objects.values_list(
        "mail_folder", "mail_uid", "mail_subject", "mail_date"
    )
    for folder, uid, subject, mail_date in rows.iterator():
        seen.setdefault((folder, uid), (subject, mail_date))

    CollectedMailLog.objects.bulk_create(
        [
            CollectedMailLog(
                mail_folder=folder,
                mail_uid=uid,
                mail_subject=(subject or "")[:500],
                mail_date=mail_date,
            )
            for (folder, uid), (subject, mail_date) in seen.items()
        ],
        batch_size=500,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_remove_collectedsettlement_uniq_collected_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedMailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_folder", models.CharField(max_length=255)),
                ("mail_uid", models.IntegerField()),
                (
                    "mail_subject",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("mail_date", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-collected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["mail_folder", "mail_uid"],
                        name="mail_collec_mail_fo_c674e4_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="collectedmaillog",
            constraint=models.UniqueConstraint(
                fields=("mail_folder", "mail_uid"), name="uniq_collected_mail_log"
            ),
        ),
        migrations.RunPython(
            backfill_from_collected, migrations.RunPython.noop
        ),
    ]
