# Generated by Django 4.2.16 on 2026-08-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_collectedmaillog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=255)),
                ('uid', models.IntegerField()),
                ('is_read', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['folder', 'uid'], name='mail_mailre_folder_0dcc17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mailreadstate',
            constraint=models.UniqueConstraint(fields=('folder', 'uid'), name='uniq_mail_read_state'),
        ),
    ]
