# Generated by Django 4.2.16 on 2026-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mailreadstate_mailreadstate_uniq_mail_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedsettlement',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
