# Generated by Django 5.0.14 on 2025-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="share_rate",
            field=models.CharField(blank=True, null=True),
        ),
    ]
