# Generated by Django 5.0.14 on 2026-01-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate", "0004_rate_create_user_rate_update_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultrate",
            name="is_domestic",
            field=models.BooleanField(default=False),
        ),
    ]
