# Generated by Django 5.0.14 on 2026-01-15 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_alter_distributortheatermap_options_and_more"),
        ("movie", "0005_movie_create_user_movie_update_user"),
        ("rate", "0005_defaultrate_is_domestic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TheaterRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일자"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일자"),
                ),
                (
                    "share_rate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="부율"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "create_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theater_rates",
                        to="movie.movie",
                        verbose_name="영화",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theater_rates",
                        to="client.theater",
                        verbose_name="상영관",
                    ),
                ),
                (
                    "update_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "관별 부율",
                "verbose_name_plural": "관별 부율 목록",
                "unique_together": {("theater", "movie", "start_date")},
            },
        ),
    ]
