# Generated by Django 5.0.14 on 2026-01-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate", "0006_theaterrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theaterrate",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="theaterrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="theaterrate",
            name="rate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theater_rates",
                to="rate.rate",
                verbose_name="공통 부율 설정",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="theaterrate",
            name="share_rate",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="관별 예외 부율"
            ),
        ),
        migrations.RemoveField(
            model_name="theaterrate",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="theaterrate",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="theaterrate",
            name="start_date",
        ),
    ]
