# Generated by Django 5.0.14 on 2026-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate", "0007_alter_theaterrate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultrate",
            name="share_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="부율",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="share_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="부율",
            ),
        ),
        migrations.AlterField(
            model_name="theaterrate",
            name="share_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="부율",
            ),
        ),
    ]
