# Generated by Django 5.0.14 on 2026-01-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "__first__"),
        ("fund", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yyyy", models.PositiveIntegerField()),
                ("mm", models.PositiveSmallIntegerField()),
                ("fund_yn", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_funds",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "yyyy", "mm")},
            },
        ),
    ]
