# Generated by Django 5.0.14 on 2026-01-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "__first__"),
        ("fund", "0002_monthlyfund"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yyyy", models.IntegerField()),
                ("mm", models.IntegerField()),
                ("dd", models.IntegerField()),
                ("fund_yn", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "yyyy", "mm", "dd")},
            },
        ),
    ]
