from django.urls import path
from .views import (CrawlerExecutionView, CrawlerHistoryView, CrawlerDownloadView, CrawlerStopView,
                    CrawlerTransformView, CrawlerScheduleOptionsView, CrawlerScheduleExportView,
                    CrawlerSpecialExportView,
                    CrawlerScheduleListView, CrawlTargetMovieView, CrawlTargetMovieDetailView,
                    CrawlTargetMovieBulkDeleteView, MegaboxScoreCrawlView,
                    MegaboxScoreAllView, MegaboxAccountView, MegaboxAccountDetailView,
                    CineQScoreAllView, CineQAccountView, CineQAccountDetailView,
                    KobisScoreAllView, KobisAccountView, KobisAccountDetailView)

urlpatterns = [
    path('run/', CrawlerExecutionView.as_view(), name='crawler_run'),
    path('stop/<int:history_id>/', CrawlerStopView.as_view(), name='crawler_stop'),
    path('transform/<int:history_id>/', CrawlerTransformView.as_view(), name='crawler_transform'),
    path('history/', CrawlerHistoryView.as_view(), name='crawler_history'),
    path('download/<int:history_id>/', CrawlerDownloadView.as_view(), name='crawler_download'),
    path('schedules/options/', CrawlerScheduleOptionsView.as_view(), name='schedule_options'),
    path('schedules/export/', CrawlerScheduleExportView.as_view(), name='schedule_export'),
    path('schedules/special_export/', CrawlerSpecialExportView.as_view(), name='schedule_special_export'),
    path('schedules/list/', CrawlerScheduleListView.as_view(), name='schedule_list'),
    path('targets/', CrawlTargetMovieView.as_view(), name='crawl_targets'),
    path('targets/bulk_delete/', CrawlTargetMovieBulkDeleteView.as_view(), name='crawl_target_bulk_delete'),
    path('targets/<int:pk>/', CrawlTargetMovieDetailView.as_view(), name='crawl_target_detail'),
    path('megabox_score/', MegaboxScoreCrawlView.as_view(), name='megabox_score_crawl'),
    path('megabox_score_all/', MegaboxScoreAllView.as_view(), name='megabox_score_all'),
    path('megabox_accounts/', MegaboxAccountView.as_view(), name='megabox_accounts'),
    path('megabox_accounts/<int:pk>/', MegaboxAccountDetailView.as_view(), name='megabox_account_detail'),
    path('cineq_score_all/', CineQScoreAllView.as_view(), name='cineq_score_all'),
    path('cineq_accounts/', CineQAccountView.as_view(), name='cineq_accounts'),
    path('cineq_accounts/<int:pk>/', CineQAccountDetailView.as_view(), name='cineq_account_detail'),
    path('kobis_score_all/', KobisScoreAllView.as_view(), name='kobis_score_all'),
    path('kobis_accounts/', KobisAccountView.as_view(), name='kobis_accounts'),
    path('kobis_accounts/<int:pk>/', KobisAccountDetailView.as_view(), name='kobis_account_detail'),
]
