# Generated by Django 5.0.14 on 2025-04-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_code", models.CharField(max_length=20, unique=True)),
                ("is_primary_movie", models.BooleanField(default=False)),
                ("title_ko", models.CharField(max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "running_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rating", models.CharField(blank=True, max_length=50, null=True)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("director", models.CharField(blank=True, max_length=100, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("closure_completed_date", models.DateField(blank=True, null=True)),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "primary_movie_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("media_type", models.CharField(blank=True, max_length=50, null=True)),
                ("audio_mode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "viewing_dimension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "screening_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "audio_dimension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dx4_viewing_dimension",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movie_distributor",
                        to="client.client",
                    ),
                ),
                (
                    "production_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_company",
                        to="client.client",
                    ),
                ),
            ],
        ),
    ]
