# Generated by Django 5.0.14 on 2026-01-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_created_date_movie_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
