# Generated by Django 4.2.16 on 2026-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='audio_dimension',
        ),
        migrations.AddField(
            model_name='movie',
            name='imax_l',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screen_x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
