# Generated by Django 4.2.16 on 2026-01-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_create_user_movie_update_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGVScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=10)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
            ],
        ),
    ]
