# Generated by Django 4.2.16 on 2026-01-26 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_cgvschedulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgvschedulelog',
            name='theater_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MovieSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('CGV', 'CGV'), ('LOTTE', 'Lotte Cinema'), ('MEGABOX', 'Megabox'), ('OTHER', 'Other')], default='CGV', max_length=20)),
                ('theater_name', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_booking_available', models.BooleanField(default=True)),
                ('booking_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.cgvschedulelog')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time'], name='movie_movie_start_t_be2554_idx'), models.Index(fields=['brand', 'theater_name'], name='movie_movie_brand_98d838_idx')],
            },
        ),
    ]
