# Generated by Django 4.2.16 on 2026-01-26 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_cgvschedulelog_theater_name_movieschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieschedule',
            unique_together={('brand', 'theater_name', 'screen_name', 'start_time')},
        ),
    ]
