# Generated by Django 4.2.16 on 2026-01-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movieschedule_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaboxScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=20)),
                ('theater_name', models.CharField(max_length=50)),
                ('response_json', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
