# Generated by Django 4.2.16 on 2026-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_megaboxschedulelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.CharField(max_length=8)),
                ('site_code', models.CharField(max_length=20)),
                ('theater_name', models.CharField(max_length=100)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
