# Generated by Django 4.2.16 on 2026-01-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_lotteschedulelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LotteScheduleLog',
        ),
        migrations.DeleteModel(
            name='MegaboxScheduleLog',
        ),
        migrations.AlterUniqueTogether(
            name='movieschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='movieschedule',
            name='raw_log',
        ),
        migrations.DeleteModel(
            name='CGVScheduleLog',
        ),
        migrations.DeleteModel(
            name='MovieSchedule',
        ),
    ]
