# Generated by Django 5.0.14 on 2026-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_delete_lotteschedulelog_delete_megaboxschedulelog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[("news", "뉴스"), ("blog", "블로그")], max_length=10
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("link", models.URLField(max_length=1000)),
                (
                    "original_link",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("pub_date", models.CharField(blank=True, default="", max_length=100)),
                ("image", models.URLField(blank=True, default="", max_length=1000)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["article_type", "query"],
                        name="movie_cache_article_0c1527_idx",
                    )
                ],
            },
        ),
    ]
