# Generated by Django 4.2.16 on 2026-02-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_cachedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_public',
        ),
    ]
