# Generated by Django 5.0.14 on 2026-04-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_alter_distributortheatermap_options_and_more"),
        ("movie", "0013_remove_movie_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="distributor_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_distributor_2",
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="distributor_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movie_distributor_3",
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_company_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_company_2",
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_company_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_company_3",
                to="client.client",
            ),
        ),
    ]
